CREATE TABLE customers
(
    id           INT8 GENERATED BY DEFAULT AS IDENTITY,
    creationtime TIMESTAMP      NOT NULL,
    creditlimit  DECIMAL(19, 2) NOT NULL,
    name         VARCHAR(255)   NOT NULL,
    version      INT4           NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE customers_credit_reservations
(
    customerid INT8           NOT NULL,
    orderid    INT8           NOT NULL,
    amount     DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (customerid, orderid),
    CONSTRAINT fk_customer
        FOREIGN KEY (customerid)
            REFERENCES customers
            ON DELETE CASCADE
);